python3 train_models.py --DIR us_import1 --emb_dim 12
python3 train_models.py --DIR us_import2 --emb_dim 12
python3 train_models.py --DIR us_import3 --emb_dim 12
python3 train_models.py --DIR us_import4 --emb_dim 12
python3 train_models.py --DIR us_import5 --emb_dim 12
python3 train_models.py --DIR us_import1 --emb_dim 16
python3 train_models.py --DIR us_import2 --emb_dim 16
python3 train_models.py --DIR us_import3 --emb_dim 16
python3 train_models.py --DIR us_import4 --emb_dim 16
python3 train_models.py --DIR us_import5 --emb_dim 16
python3 train_models.py --DIR us_import1 --emb_dim 20
python3 train_models.py --DIR us_import2 --emb_dim 20
python3 train_models.py --DIR us_import3 --emb_dim 20
python3 train_models.py --DIR us_import4 --emb_dim 20
python3 train_models.py --DIR us_import5 --emb_dim 20
python3 train_models.py --DIR us_import1 --emb_dim 24
python3 train_models.py --DIR us_import2 --emb_dim 24
python3 train_models.py --DIR us_import3 --emb_dim 24
python3 train_models.py --DIR us_import4 --emb_dim 24
python3 train_models.py --DIR us_import5 --emb_dim 24

