python3.7 accuracy_check.py --DIR us_import1 --feedback_size 10 --top_K 10
python3.7 accuracy_check.py --DIR us_import2 --feedback_size 10 --top_K 10
python3.7 accuracy_check.py --DIR us_import3 --feedback_size 10 --top_K 10
python3.7 accuracy_check.py --DIR us_import4 --feedback_size 10 --top_K 10
python3.7 accuracy_check.py --DIR us_import1 --feedback_size 10 --top_K 20
python3.7 accuracy_check.py --DIR us_import2 --feedback_size 10 --top_K 20
python3.7 accuracy_check.py --DIR us_import3 --feedback_size 10 --top_K 20
python3.7 accuracy_check.py --DIR us_import4 --feedback_size 10 --top_K 20
python3.7 accuracy_check.py --DIR us_import1 --feedback_size 10 --top_K 30
python3.7 accuracy_check.py --DIR us_import2 --feedback_size 10 --top_K 30
python3.7 accuracy_check.py --DIR us_import3 --feedback_size 10 --top_K 30
python3.7 accuracy_check.py --DIR us_import4 --feedback_size 10 --top_K 30
python3.7 accuracy_check.py --DIR us_import1 --feedback_size 10 --top_K 40
python3.7 accuracy_check.py --DIR us_import2 --feedback_size 10 --top_K 40
python3.7 accuracy_check.py --DIR us_import3 --feedback_size 10 --top_K 40
python3.7 accuracy_check.py --DIR us_import4 --feedback_size 10 --top_K 40
python3.7 accuracy_check.py --DIR us_import1 --feedback_size 10 --top_K 50
python3.7 accuracy_check.py --DIR us_import2 --feedback_size 10 --top_K 50
python3.7 accuracy_check.py --DIR us_import3 --feedback_size 10 --top_K 50
python3.7 accuracy_check.py --DIR us_import4 --feedback_size 10 --top_K 50