python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &
python3 accuracy_check.py --DIR us_import1  &